language: elixir

elixir:
  - '1.0.5'
otp_release: '17.4'

env:
  - TEST_DIR=bouncingbullet
  - TEST_DIR=bullet
  - TEST_DIR=clock
  - TEST_DIR=observable
  - TEST_DIR=player
  - TEST_DIR=world
  - TEST_DIR=integration

script: cd $TEST_DIR && mix test
